(function () {
  'use strict';
  const $ = id => document.getElementById(id);
  const config = window.APP_CONFIG || {};
  const months = Array.from({length:53},(_,i)=>{const d=new Date(2026,8+i,1);return {year:d.getFullYear(),month:d.getMonth()+1,label:`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,'0')}`}});
  const header = ['姓名','專案名稱','設置容量(kW)','建置地點','進場日期','併聯日期',...months.map(x=>x.label)];
  const fieldMap = {name:'person_name',project:'project_name',start:'start_date',end:'end_date'};
  const state = {client:null,assignments:new Map(),summary:new Map(),contacts:[],projects:[],shown:81,channel:null,referenceTimer:null};
  function message(t,error=false){$('status').textContent=t;$('status').style.color=error?'#b3261e':'#176b35'}
  function authMessage(t,error=false){$('auth-message').textContent=t;$('auth-message').className=error?'error':''}
  function td(text='',className=''){const c=document.createElement('td');c.textContent=text;c.className=className;return c}
  function makeSelect(value,options,emptyLabel,change){const el=document.createElement('select');const all=['',...options.filter(Boolean)];if(value&&!all.includes(value))all.push(value);for(const v of all){const o=document.createElement('option');o.value=v;o.textContent=v||emptyLabel;if(v===value)o.selected=true;el.append(o)}el.addEventListener('change',()=>change(el.value));return el}
  function monthActive(row,m){if(!row.start_date||!row.end_date)return false;const s=String(row.start_date).slice(0,10),e=String(row.end_date).slice(0,10);if(s>e)return false;const first=`${m.year}-${String(m.month).padStart(2,'0')}-01`;const last=new Date(m.year,m.month,0);const final=`${m.year}-${String(m.month).padStart(2,'0')}-${String(last.getDate()).padStart(2,'0')}`;return s<=final&&e>=first}
  function projectByName(name){return state.projects.find(p=>p.name===name)}
  function renderSchedule(){
    const table=$('schedule-table');table.replaceChildren();const cols=document.createElement('colgroup');[42,110,220,120,120,118,118,...months.map(()=>66)].forEach(w=>{const col=document.createElement('col');col.style.width=w+'px';cols.append(col)});table.append(cols);
    const thead=document.createElement('thead'),tr=document.createElement('tr');const n=document.createElement('th');n.className='rownum';n.textContent='';tr.append(n);header.forEach((h,i)=>{const c=document.createElement('th');c.textContent=h;if(i>=6)c.className='month';tr.append(c)});thead.append(tr);table.append(thead);
    const body=document.createElement('tbody');const names=state.contacts.map(x=>x[1]).filter(Boolean),projects=state.projects.map(x=>x.name);
    for(let index=2;index<=state.shown+1;index++){
      const row=state.assignments.get(index)||{},r=document.createElement('tr');r.append(td(index,'rownum'));
      const a=td();a.append(makeSelect(row.person_name||'',names,'選擇姓名',v=>save(index,'name',v)));r.append(a);
      const b=td();b.append(makeSelect(row.project_name||'',projects,'選擇專案',v=>save(index,'project',v)));r.append(b);
      const p=projectByName(row.project_name),missing=row.project_name&&!p;
      r.append(td(p?.capacity||(missing?'原專案已移除':''),'computed'+(missing?' missing':'')));
      r.append(td(p?.location||'','computed'));
      for(const [field,val] of [['start',row.start_date],['end',row.end_date]]){const cell=td();const input=document.createElement('input');input.type='date';input.value=val||'';input.setAttribute('aria-label',`${index} 列${field==='start'?'進場':'併聯'}日期`);input.addEventListener('change',()=>save(index,field,input.value));cell.append(input);r.append(cell)}
      for(const m of months)r.append(td(monthActive(row,m)?'1':'','month'+(monthActive(row,m)?' active-month':'')));
      body.append(r)
    }table.append(body)
  }
  function renderSummary(){const table=$('summary-table');table.replaceChildren();const head=document.createElement('thead'),r=document.createElement('tr');r.append(Object.assign(document.createElement('th'),{className:'rownum'}));for(const h of ['姓名',...months.map(x=>x.label)]){const c=document.createElement('th');c.textContent=h;if(h!=='姓名')c.className='month';r.append(c)}head.append(r);table.append(head);const body=document.createElement('tbody');const names=state.contacts.map(x=>x[1]).filter(Boolean);for(let i=1;i<=30;i++){const row=document.createElement('tr');row.append(td(i+1,'rownum'));const name=state.summary.get(i)||'';const select=td();select.append(makeSelect(name,names,'選擇姓名',v=>saveSummary(i,v)));row.append(select);for(const m of months){const count=name?[...state.assignments.values()].filter(a=>a.person_name===name&&monthActive(a,m)).length:0;row.append(td(name?String(count):'','month'+(count?' load'+Math.min(3,count):'')))}body.append(row)}table.append(body)}
  function renderReferences(){const ct=$('contacts-table');ct.replaceChildren();const ch=document.createElement('thead'),cr=document.createElement('tr');['部門','姓名','員工編號','職稱','分機','電子郵件'].forEach(h=>{const t=document.createElement('th');t.textContent=h;cr.append(t)});ch.append(cr);ct.append(ch);const cb=document.createElement('tbody');state.contacts.forEach(row=>{const tr=document.createElement('tr');for(let i=0;i<6;i++)tr.append(td(row[i]||''));cb.append(tr)});ct.append(cb);
    const pt=$('projects-table');pt.replaceChildren();const ph=document.createElement('thead'),pr=document.createElement('tr');pr.append(Object.assign(document.createElement('th'),{className:'rownum'}));state.projects.forEach((_,i)=>{const h=document.createElement('th');h.textContent=columnName(i+1);h.style.minWidth='190px';pr.append(h)});ph.append(pr);pt.append(ph);const pb=document.createElement('tbody');for(const [label,key] of [['1','name'],['2','capacity'],['3','location']]){const tr=document.createElement('tr');tr.append(td(label,'rownum'));state.projects.forEach(p=>tr.append(td(p[key]||'')));pb.append(tr)}pt.append(pb)}
  function columnName(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
  function render(){renderSchedule();renderSummary();renderReferences()}
  async function save(index,field,value){message('儲存中…');const {error}=await state.client.rpc('set_assignment_cell',{p_row_index:index,p_field:field,p_value:value||null});if(error){message(`儲存失敗：${error.message}`,true);await loadAssignments();return}const row=state.assignments.get(index)||{row_index:index};row[fieldMap[field]]=value||null;state.assignments.set(index,row);renderSchedule();renderSummary();message('已儲存')}
  async function saveSummary(index,value){const {error}=await state.client.rpc('set_summary_person',{p_slot:index,p_person:value||null});if(error){message(`儲存失敗：${error.message}`,true);return}state.summary.set(index,value);renderSummary();message('已儲存')}
  async function loadAssignments(){const {data,error}=await state.client.from('assignments').select('row_index,person_name,project_name,start_date,end_date').order('row_index');if(error)throw error;state.assignments=new Map((data||[]).map(x=>[x.row_index,x]));const s=await state.client.from('summary_people').select('slot,person_name').order('slot');if(s.error)throw s.error;state.summary=new Map((s.data||[]).map(x=>[x.slot,x.person_name]));renderSchedule();renderSummary()}
  async function loadReferences(){message('正在同步 Google Sheet…');const {data,error}=await state.client.functions.invoke('sheet-reference');if(error)throw error;if(!data||!Array.isArray(data.contacts)||!Array.isArray(data.projects))throw Error('同步資料格式不正確');state.contacts=data.contacts;state.projects=data.projects;render();message('已同步原始試算表（'+new Date().toLocaleTimeString('zh-TW')+'）')}
  function subscribe(){if(state.channel)state.client.removeChannel(state.channel);state.channel=state.client.channel('manpower-live').on('postgres_changes',{event:'*',schema:'public',table:'assignments'},()=>loadAssignments().catch(e=>message(e.message,true))).on('postgres_changes',{event:'*',schema:'public',table:'summary_people'},()=>loadAssignments().catch(e=>message(e.message,true))).subscribe()}
  async function signedIn(session){if(!session?.user?.email_confirmed_at){$('auth').hidden=false;$('app').hidden=true;authMessage('請先到信箱按驗證連結，再登入。');return} $('auth').hidden=true;$('app').hidden=false;$('account').textContent=session.user.email;try{await Promise.all([loadAssignments(),loadReferences()]);subscribe();clearInterval(state.referenceTimer);state.referenceTimer=setInterval(()=>loadReferences().catch(e=>message(`同步失敗：${e.message}`,true)),60000)}catch(e){message(`讀取失敗：${e.message}`,true)}}
  async function logout(){clearInterval(state.referenceTimer);if(state.channel)await state.client.removeChannel(state.channel);await state.client.auth.signOut();$('app').hidden=true;$('auth').hidden=false}
  function init(){if(!window.supabase?.createClient||!config.supabaseUrl?.startsWith('https://')||!config.supabasePublishableKey||config.supabasePublishableKey.startsWith('PASTE_')){authMessage('請先在 config.js 填入 Supabase Project URL 與 Publishable key。',true);return}state.client=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);
    $('auth-form').addEventListener('submit',async e=>{e.preventDefault();authMessage('登入中…');const {error}=await state.client.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});authMessage(error?error.message:'登入成功',!!error)});
    $('signup').addEventListener('click',async()=>{if(!$('email').checkValidity()||!$('password').checkValidity()){authMessage('請先輸入有效電子郵件及至少 6 碼密碼。',true);return}authMessage('正在建立帳號…');const {error}=await state.client.auth.signUp({email:$('email').value.trim(),password:$('password').value,options:{emailRedirectTo:location.origin+location.pathname}});authMessage(error?error.message:'帳號已建立，請到信箱完成驗證，再回來登入。',!!error)});
    $('logout').addEventListener('click',logout);$('refresh').addEventListener('click',()=>Promise.all([loadAssignments(),loadReferences()]).catch(e=>message(e.message,true)));$('more').addEventListener('click',()=>{state.shown=Math.min(980,state.shown+100);renderSchedule();$('more').disabled=state.shown===980});document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab)}));state.client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){clearInterval(state.referenceTimer);$('app').hidden=true;$('auth').hidden=false}else if(event==='SIGNED_IN'||event==='INITIAL_SESSION')setTimeout(()=>signedIn(session),0)})}
  init();
})();
